baseURL = "https://moriarty-management.netlify.app"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "Moriarty Management"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Designed by [Tropicaldo](https://tropicaldo.com) & Developed by [Marco](https://tropicaldo.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
name = "about"
url = "#about"
weight = 1
[[Languages.en.menu.main]]
name = "actors"
url = "#actor"
weight = 4
[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 7
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Designed by [Tropicaldo](https://tropicaldo.com) & Developed by [Marco](https://tropicaldo.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.main]]
name = "sur"
url = "#about"
weight = 1
[[Languages.fr.menu.main]]
name = "acteurs"
url = "#actor"
weight = 4
[[Languages.fr.menu.main]]
name = "contact"
url = "#contact"
weight = 7
[params]
author = "Tropicaldo"
description = "Moriarty Management client site"
google_analytics_id = ""
logo = "images/mm_small_logo.jpg"
post_share = true
isMultiLingual = false
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = "images/logo.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
